# Generated by Django 4.0 on 2022-01-01 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditionalinformation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_information', to='shared.personalshowcaseuser', verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='website',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='websites', to='shared.personalshowcaseuser', verbose_name='Usuário'),
        ),
    ]
