# Generated by Django 4.0 on 2021-12-31 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_useradditionalinformation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalshowcaseuser',
            old_name='title',
            new_name='professional_title',
        ),
        migrations.AlterField(
            model_name='personalshowcaseuser',
            name='additional_information',
            field=models.ManyToManyField(blank=True, to='shared.UserAdditionalInformation', verbose_name='Informações Adicionais'),
        ),
        migrations.AlterField(
            model_name='personalshowcaseuser',
            name='websites',
            field=models.ManyToManyField(blank=True, to='shared.Website'),
        ),
    ]
