# Generated by Django 4.0 on 2021-12-31 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0003_rename_title_personalshowcaseuser_professional_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalshowcaseuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto de Perfil'),
        ),
    ]
