# Generated by Django 4.0 on 2022-01-04 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_article_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='tag_color',
            field=models.CharField(default='', max_length=9, verbose_name='Cor da Tag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.blog'),
        ),
    ]
