# Generated by Django 4.0 on 2021-12-19 03:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('proficiency', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Nível de Proficiência')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('proficiency', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Nível de Proficiência')),
            ],
            options={
                'verbose_name': 'Linguagem de Programação',
                'verbose_name_plural': 'Linguagens de Programação',
            },
        ),
        migrations.CreateModel(
            name='SoftSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('proficiency', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Nível de Proficiência')),
            ],
            options={
                'verbose_name': 'Habilidade Leve',
                'verbose_name_plural': 'Habilidades Leves',
            },
        ),
        migrations.CreateModel(
            name='TechSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('proficiency', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Nível de Proficiência')),
            ],
            options={
                'verbose_name': 'Habilidade Técnica',
                'verbose_name_plural': 'Habilidades Técnicas',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=100, verbose_name='Cargo')),
                ('company', models.CharField(max_length=100, verbose_name='Empresa')),
                ('start_date', models.DateTimeField(verbose_name='Data de Início')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Encerramento')),
                ('current', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Experiência',
                'verbose_name_plural': 'Experiências',
            },
        ),
        migrations.CreateModel(
            name='RoleActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(verbose_name='Atividade Exercida')),
                ('work_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.workexperience')),
            ],
            options={
                'verbose_name': 'Atividade do Cargo',
                'verbose_name_plural': 'Atividades do Cargo',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('languages', models.ManyToManyField(to='resume.Language')),
                ('programming_languages', models.ManyToManyField(to='resume.ProgrammingLanguage')),
                ('soft_skills', models.ManyToManyField(to='resume.SoftSkill')),
                ('tech_skills', models.ManyToManyField(to='resume.TechSkill')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shared.personalshowcaseuser')),
                ('work_experiences', models.ManyToManyField(to='resume.WorkExperience')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
