# Generated by Django 4.0 on 2021-12-28 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.personalshowcaseuser'),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='carrousel_items',
            field=models.ManyToManyField(to='resume.CarrouselItem', verbose_name='Itens do Carrossel'),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resume.resume', verbose_name='Resume'),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.personalshowcaseuser', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='techskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.personalshowcaseuser'),
        ),
        migrations.AddField(
            model_name='softskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.personalshowcaseuser'),
        ),
        migrations.AddField(
            model_name='roleactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.personalshowcaseuser'),
        ),
        migrations.AddField(
            model_name='roleactivity',
            name='work_experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.workexperience'),
        ),
        migrations.AddField(
            model_name='resume',
            name='languages',
            field=models.ManyToManyField(to='resume.Language'),
        ),
        migrations.AddField(
            model_name='resume',
            name='programming_languages',
            field=models.ManyToManyField(to='resume.ProgrammingLanguage'),
        ),
        migrations.AddField(
            model_name='resume',
            name='soft_skills',
            field=models.ManyToManyField(to='resume.SoftSkill'),
        ),
        migrations.AddField(
            model_name='resume',
            name='tech_skills',
            field=models.ManyToManyField(to='resume.TechSkill'),
        ),
        migrations.AddField(
            model_name='resume',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='shared.personalshowcaseuser'),
        ),
        migrations.AddField(
            model_name='resume',
            name='work_experiences',
            field=models.ManyToManyField(blank=True, to='resume.WorkExperience'),
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.personalshowcaseuser'),
        ),
        migrations.AddField(
            model_name='language',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.personalshowcaseuser'),
        ),
    ]
