# Generated by Django 4.0 on 2022-01-01 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.resume', verbose_name='Resume'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='resume.resume', verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='programminglanguage',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programming_languages', to='resume.resume', verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='techskill',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_skills', to='resume.resume', verbose_name='Resume'),
        ),
    ]
