# Generated by Django 4.0 on 2022-01-07 04:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_useradditionalinformation_created_by_and_more'),
        ('resume', '0003_workexperience_resume_alter_language_resume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome da Categoria')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Categoria de Habilidades Personalizada',
                'verbose_name_plural': 'Categorias de Habilidades Personalizadas',
            },
        ),
        migrations.CreateModel(
            name='CustomSkillCategorySkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('proficiency', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Nível de Proficiência')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.personalshowcaseuser', verbose_name='Usuário')),
                ('custom_skill_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.customskillcategory', verbose_name='Categoria de Habilidade Personalizada')),
            ],
            options={
                'verbose_name': 'Habilidade da Categoria Personalizada',
                'verbose_name_plural': 'Habilidades da Categoria Personalizada',
            },
        ),
    ]
