# Generated by Django 4.0 on 2022-01-07 05:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_useradditionalinformation_created_by_and_more'),
        ('resume', '0004_customskillcategory_customskillcategoryskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='customskillcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customskillcategory',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shared.personalshowcaseuser', verbose_name='Usuário'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customskillcategory',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
