# Generated by Django 4.0 on 2022-01-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_customskillcategory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customskillcategory',
            name='use_on_resume',
            field=models.BooleanField(default=True, verbose_name='Utilizar no Website?'),
        ),
    ]
