# Generated by Django 4.0 on 2022-01-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_customskillcategory_use_on_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='customskillcategory',
            name='style',
            field=models.CharField(choices=[('Circular', 'Circular'), ('Linear', 'Linear'), ('Check Mark', 'Check Mark')], default='Check Mark', max_length=20),
        ),
    ]
