# Generated by Django 4.0 on 2022-01-09 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0002_alter_useradditionalinformation_created_by_and_more'),
        ('resume', '0007_customskillcategory_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workexperience',
            old_name='company',
            new_name='company_name',
        ),
        migrations.AlterField(
            model_name='customskillcategory',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_skill_categories', to='resume.resume', verbose_name='Resume'),
        ),
        migrations.AlterField(
            model_name='customskillcategory',
            name='style',
            field=models.CharField(choices=[('Circular', 'Circular'), ('Linear', 'Linear'), ('Check Mark', 'Check Mark')], default='Check Mark', max_length=20, verbose_name='Estilo'),
        ),
        migrations.AlterField(
            model_name='customskillcategoryskill',
            name='custom_skill_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_skill_category_skills', to='resume.customskillcategory', verbose_name='Categoria de Habilidade Personalizada'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Encerramento'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_date',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.CreateModel(
            name='EducationHistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('institution_name', models.CharField(max_length=100, verbose_name='Instituição')),
                ('start_date', models.DateField(verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Encerramento')),
                ('graduation_name', models.CharField(max_length=75, verbose_name='Nome do Curso')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.personalshowcaseuser', verbose_name='Usuário')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_history_items', to='resume.resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Item do Histórico Educacional',
                'verbose_name_plural': 'Itens do Histórico Educacional',
            },
        ),
    ]
