# Generated by Django 4.0 on 2022-01-09 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_rename_company_workexperience_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationhistoryitem',
            name='observation',
            field=models.CharField(default='', max_length=100, verbose_name='Observações'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='resume.resume', verbose_name='Resume'),
        ),
    ]
