# Generated by Django 4.0 on 2021-12-31 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
        ('portfolio', '0001_initial'),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('personal_url', models.CharField(max_length=50, unique=True, verbose_name='Url pessoal')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.personalshowcaseuser', verbose_name='Usuário')),
                ('portfolio', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio', verbose_name='Portfolio')),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resume.resume', verbose_name='Resume')),
            ],
            options={
                'verbose_name': 'Conteúdo do Site',
                'verbose_name_plural': 'Conteúdo do Site',
            },
        ),
        migrations.CreateModel(
            name='CarrouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=60, verbose_name='Item do carrossel do Banner')),
                ('position', models.IntegerField(verbose_name='Posição no carrossel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.personalshowcaseuser', verbose_name='Usuário')),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.websitecontent', verbose_name='Website')),
            ],
            options={
                'verbose_name': 'Item do Carrossel (Website Banner)',
                'verbose_name_plural': 'Itens do Carrossel (Website Banner)',
            },
        ),
    ]
