# Generated by Django 4.0 on 2021-12-30 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0003_remove_websitecontent_carrousel_items_and_more'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=60, verbose_name='Item do carrossel do Banner')),
                ('position', models.IntegerField(verbose_name='Posição no carrossel')),
            ],
            options={
                'verbose_name': 'Item do Carrossel (Website Banner)',
                'verbose_name_plural': 'Itens do Carrossel (Website Banner)',
            },
        ),
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('carrousel_items', models.ManyToManyField(to='website.CarrouselItem', verbose_name='Itens do Carrossel')),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resume.resume', verbose_name='Resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.personalshowcaseuser', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Conteúdo do Site',
            },
        ),
    ]
