# Generated by Django 4.0 on 2022-01-01 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrouselitem',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrousel_items', to='website.websitecontent', verbose_name='Website'),
        ),
    ]
