# Generated by Django 4.0 on 2022-01-01 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_websitecontent_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecontent',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem do Banner'),
        ),
    ]
