# Generated by Django 4.0 on 2022-01-03 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_article_blog'),
        ('website', '0004_alter_websitecontent_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecontent',
            name='blog',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.blog', verbose_name='Blog'),
            preserve_default=False,
        ),
    ]
