# Generated by Django 4.0 on 2021-12-31 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learn_me', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.personalshowcaseuser', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='topic',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_me.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.personalshowcaseuser', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='step',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shared.personalshowcaseuser', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='step',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn_me.topic', verbose_name='Tópico'),
        ),
    ]
