# Generated by Django 4.0 on 2021-12-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Projeto')),
                ('description', models.TextField(verbose_name='Descrição do Projeto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem do Projeto')),
                ('url', models.CharField(max_length=255, verbose_name='URL do Projeto')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
            },
        ),
    ]
